apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework.fullname" (dict "context" . "component" "api") }}
  labels:
    {{- include "homework.labels" (dict "context" . "component" "api") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "homework.selectorLabels" (dict "context" . "component" "api") | nindent 4 }}
